services:
  localstack:
    image: localstack/localstack:s3-latest
    container_name: localstack-aws
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
    environment:
      - DEBUG=${DEBUG:-0}
#    environment:
#      - SERVICES=s3,lambda
#      - DEBUG=1
#      - SKIP_SSL_CERT_DOWNLOAD =1
#      - DATA_DIR=/tmp/localstack/data
#      - LAMBDA_EXECUTOR=docker
#      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - aws-local

networks:
  aws-local:
    driver: bridge
