name: 'Terraform OIDC'

on:
  push:
    branches:
      - main
    paths:
      - 'oidc/*'
      - '.github/workflows/tf-oidc.yaml'
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy resources?'
        required: true
        default: 'false'
        type: boolean  

permissions:
  id-token: write
  contents: read


jobs:
  tf-oidc:
    name: 'Terraform OIDC'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ vars.REGION }}
          role-to-assume: ${{ vars.OIDC_ROLE }}
          role-session-name: IAM-Github-Actions-TF

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: v1.13.2

      - name: 'Terraform Init'
        working-directory: oidc
        run: terraform init
      
      - name: 'Terraform Plan'
        working-directory: oidc
        run: |
          if [ "${{ github.event.inputs.destroy }}" == "true" ]; then
            terraform plan -destroy -input=false -out=tfplan
          else
            terraform plan -input=false -out=tfplan
          fi

      - name: 'Upload Terraform Plan'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: oidc/tfplan


  tf-oidc-apply:
    needs: tf-oidc
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ vars.REGION }}
          role-to-assume: ${{ vars.OIDC_ROLE }}
          role-session-name: IAM-Github-Actions-TF

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: v1.13.2

      - name: 'Terraform Init'
        working-directory: oidc
        run: terraform init

      - name: 'Download Terraform Plan'
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: oidc

      - name: 'Terraform Apply'
        working-directory: oidc
        run: terraform apply -auto-approve tfplan

